name: lav_home
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  jaspr_router: ^0.7.0
  markdown: ^7.3.0
  universal_web: ^1.1.0+2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.1.1
  jaspr_builder: ^0.19.0
  jaspr_lints: ^0.3.0
  lints: ^6.0.0

jaspr:
  mode: static

